INSERT INTO COMPRA (
    ID,
    VALOR_COMPRA_TOTAL,
    URL_FACTURA_ELECTRONICA,
    ESTADO_COMPRA,
    COMPRADOR,
    FECHA_COMPRA
) VALUES (
    (SELECT (MAX(ID) + 1) FROM COMPRA),
    0,
    'https://mashable.com/mauris.jsp',
    'CREADA',
    '3896442104',
    '28-Nov-2021'
);

SELECT COMPRA.ID AS ID_COMPRA,
    ID_PRODUCTO,
    CANT_UNIDADES_COMPRADAS
FROM PRODUCTOS_COMPRA
    FULL OUTER JOIN COMPRA
    ON ID_COMPRA = COMPRA.ID
    FULL OUTER JOIN USUARIO
    ON COMPRADOR = USUARIO.NUMERO_DOCUMENTO
WHERE COMPRADOR = 3896442104 AND
    COMPRA.ID = 1;