CREATE VIEW PRODUCTOS_COMPRADOS AS (
    SELECT SEMANA,
    ID_PRODUCTO,
    COMPRAS,
    ID_SUCURSAL FROM ( (SELECT TRUNC(FECHA_COMPRA, 'IW') AS SEMANA, ID_PRODUCTO, COUNT(ID_PRODUCTO) AS COMPRAS, ID_SUCURSAL FROM USUARIOS_CON_COMPRA GROUP BY FECHA_COMPRA, ID_PRODUCTO, ID_SUCURSAL ORDER BY FECHA_COMPRA) INNER JOIN (SELECT CODIGO_BARRAS, NOMBRE FROM PRODUCTO) ON CODIGO_BARRAS = ID_PRODUCTO ) GROUP BY SEMANA,
    ID_PRODUCTO,
    COMPRAS,
    ID_SUCURSAL
);

SELECT *
FROM PRODUCTOS_COMPRADOS;

SELECT SEMANA_CONSULTA,
    NUM_COMPRAS AS VALORES_MAXIMOS,
    ID_PRODUCTO AS PRODUCTO_MAXIMO,
    ID_SUCURSAL
FROM ( (
        SELECT SEMANA       AS SEMANA_CONSULTA,
            MAX(COMPRAS) AS NUM_COMPRAS,
            ID_SUCURSAL  AS ID
        FROM PRODUCTOS_COMPRADOS
        GROUP BY SEMANA,
            ID_SUCURSAL
        ORDER BY SEMANA
    ) INNER JOIN (
        SELECT *
        FROM PRODUCTOS_COMPRADOS
    ) ON NUM_COMPRAS = COMPRAS AND
    ID_SUCURSAL = ID );

SELECT NUM_COMPRAS AS VALORES_MINIMOS,
    ID_PRODUCTO AS PRODUCTO_MINIMO,
    ID_SUCURSAL
FROM ( (
        SELECT SEMANA       AS SEMANA_CONSULTA,
            MIN(COMPRAS) AS NUM_COMPRAS,
            ID_SUCURSAL  AS ID
        FROM PRODUCTOS_COMPRADOS
        GROUP BY SEMANA,
            ID_SUCURSAL
        ORDER BY SEMANA
    ) INNER JOIN (
        SELECT *
        FROM PRODUCTOS_COMPRADOS
    ) ON NUM_COMPRAS = COMPRAS AND
    ID_SUCURSAL = ID );