CREATE TABLE SUCURSAL (
    ID INT,
    CIUDAD VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    SIZE_SUCURSAL VARCHAR(255) CHECK(SUCURSAL IN ('Small', 'Medium', 'Big')),
    SUPERMERCADO INT FOREIGN KEY REFERENCES SUPERMERCADO(NIT),
    PRIMARY KEY ID

);