
SELECT ID_TIENDA, NOMBRE, SUM() AS SUMA_VENTAS FROM (
    (
    (   SELECT ID, COMPRADOR, VALOR_COMPRA_TOTAL 
        FROM COMPRA)
    INNER JOIN
    (   SELECT NUMERO_DOCUMENTO, ID_SUCURSAL 
        FROM USUARIO)
    ON USUARIO.NUMERO_DOCUMENTO = COMPRA.COMPRADOR
    ) COMPRAS
    INNER JOIN
    (
        SELECT ID AS ID_TIENDA, NOMBRE 
        FROM SUCURSAL)
    ON SUCURSAL.ID = COMPRAS.ID_SUCURSAL
) 
GROUP BY ID_TIENDA, NOMBRE
ORDER BY SUMA_VENTAS DESC;