SELECT ID, COUNT(ID) AS VECES_COMPRADO, CODIGO_BARRAS, NOMBRE
FROM 
(
    (
    (
        SELECT ID, ID_PRODUCTO
        FROM PROMOCION
    )
    INNER JOIN
    (
        SELECT CODIGO_BARRAS, NOMBRE
        FROM  PRODUCTO
    )
    ON PROMOCION.ID_PRODUCTO = PRODUCTO.CODIGO_BARRAS
    ) PROM
    INNER JOIN
    (
        SELECT *
        FROM PRODUCTOS_COMPRA
    )
    ON PRODUCTOS_COMPRA.ID_PRODUCTO = PROM.CODIGO_BARRAS

) GROUP BY ID, CODIGO_BARRAS, NOMBRE
ORDER BY VECES_COMPRADO DESC;