SELECT ID, TIPO_CONTENEDOR, (SUM(MEDIDA)/CAPACIDAD_MAXIMA_PESO)*100 AS PORCENTAJE_ALMACENAMIENTO
FROM (
    SELECT * FROM CONTENEDOR
    INNER JOIN
    (SELECT * FROM ALMACENAMIENTO_PRODUCTO) ALM
    ON CONTENEDOR.ID = ALM.ID_CONTENEDOR_ACTUAL
    INNER JOIN
    (SELECT * FROM MEDICION_PRODUCTO) MED 
    ON MED.ID = ALM.ID
)
WHERE (ID_SUCURSAL = '1')
GROUP BY ID, TIPO_CONTENEDOR, CAPACIDAD_MAXIMA_PESO;