-- Filter products by characteristics

-- Price range
SELECT *
FROM PRODUCTO
    INNER JOIN DETALLES_PRODUCTO
    ON INFO_DETALLES = DETALLES_PRODUCTO.ID
WHERE PRECIO BETWEEN 0 AND 600
ORDER BY PRECIO DESC;

-- Subsequent product expiration date
SELECT *
FROM PRODUCTO
WHERE '14-NOV-24' < FECHA_VENCIMIENTO
ORDER BY FECHA_VENCIMIENTO ASC;

-- Weight or Volume in range
SELECT *
FROM PRODUCTO
    INNER JOIN MEDICION_PRODUCTO
    ON INFO_MEDICION = MEDICION_PRODUCTO.ID
WHERE MEDIDA BETWEEN 8000 AND 9000
ORDER BY MEDIDA DESC;

-- Sold by certain supplier
SELECT *
FROM PRODUCTO
    INNER JOIN PEDIDOS_PROVEEDOR
    ON PRODUCTO.ID_PEDIDO = PEDIDOS_PROVEEDOR.ID_PEDIDO
WHERE ID_PROVEEDOR = '1280637439';

-- Available in certain city
SELECT *
FROM PRODUCTO
    INNER JOIN ALMACENAMIENTO_PRODUCTO
    ON INFO_ALMACENAMIENTO = ALMACENAMIENTO_PRODUCTO.ID
    INNER JOIN CONTENEDOR
    ON ID_CONTENEDOR_ACTUAL = CONTENEDOR.ID
    INNER JOIN SUCURSAL
    ON CONTENEDOR.ID_SUCURSAL = SUCURSAL.ID
WHERE CIUDAD = 'Miami' AND
    EXISTENCIAS_ACTUALES > 0;

-- Available in certain subsidiary
SELECT *
FROM PRODUCTO
    INNER JOIN ALMACENAMIENTO_PRODUCTO
    ON INFO_ALMACENAMIENTO = ALMACENAMIENTO_PRODUCTO.ID
    INNER JOIN CONTENEDOR
    ON ID_CONTENEDOR_ACTUAL = CONTENEDOR.ID
    INNER JOIN SUCURSAL
    ON CONTENEDOR.ID_SUCURSAL = SUCURSAL.ID
WHERE SUCURSAL.NOMBRE = 'brockwello' AND
    EXISTENCIAS_ACTUALES > 0;

-- Search by type or category
SELECT *
FROM PRODUCTO
WHERE CATEGORIA = 'Abarrote' OR
    TIPO_PRODUCTO = 'Books';

-- Have sold more than X units in a range of dates
SELECT *
FROM (
        SELECT ID_PRODUCTO,
            SUM(CANT_UNIDADES_COMPRADAS) AS TOTAL_UNIDADES_COMPRADAS
        FROM PRODUCTOS_COMPRA
        WHERE ID_COMPRA IN (
                SELECT ID_COMPRA
                FROM PRODUCTOS_COMPRA
                    INNER JOIN COMPRA
                    ON ID_COMPRA = ID
                WHERE FECHA_COMPRA BETWEEN '28-NOV-21' AND '27-MAY-22'
            )
        GROUP BY ID_PRODUCTO
    )
    INNER JOIN PRODUCTO
    ON ID_PRODUCTO = PRODUCTO.CODIGO_BARRAS
WHERE TOTAL_UNIDADES_COMPRADAS > 1501;