-- Show sales of SuperAndes to a given customer, in a range of dates
SELECT *
FROM COMPRA
WHERE FECHA_COMPRA BETWEEN '28-NOV-21' AND '27-MAY-22'
AND COMPRADOR = '3896442104';

-- Show sales by products of SuperAndes to a given customer, in a range of dates
SELECT *
FROM COMPRA
INNER JOIN PRODUCTOS_COMPRA ON ID_COMPRA = ID
INNER JOIN PRODUCTO ON ID_PRODUCTO = PRODUCTO.CODIGO_BARRAS
INNER JOIN DETALLES_PRODUCTO ON DETALLES_PRODUCTO.ID = INFO_DETALLES
WHERE FECHA_COMPRA BETWEEN '28-NOV-21' AND '27-MAY-22'
AND COMPRADOR = '3896442104';