DROP VIEW DATOS_COMPRAS;

CREATE VIEW DATOS_COMPRAS AS
SELECT ID, NOMBRE_PRODUCTO AS NOMBRE, CANT_UNIDADES_COMPRADAS, VALOR_COMPRA_TOTAL,FECHA_COMPRA, CODIGO_BARRAS, ID_SUCURSAL FROM
(
    SELECT * FROM COMPRA
    FULL OUTER JOIN(SELECT ID_COMPRA, ID_PRODUCTO, CANT_UNIDADES_COMPRADAS FROM PRODUCTOS_COMPRA) 
    ON COMPRA.ID = ID_COMPRA
    FULL OUTER JOIN(SELECT CODIGO_BARRAS, NOMBRE AS NOMBRE_PRODUCTO, TIPO_PRODUCTO FROM PRODUCTO)
    ON ID_PRODUCTO = CODIGO_BARRAS
    INNER JOIN(SELECT NUMERO_DOCUMENTO, ID_SUCURSAL FROM USUARIO)
    ON COMPRADOR = NUMERO_DOCUMENTO
);

SELECT * FROM DATOS_COMPRAS;


CREATE VIEW MAYOR_DEMANDA AS
SELECT CODIGO_BARRAS, NOMBRE, NULL AS DINERO_ADQUIRIDO, SUM(CANT_UNIDADES_COMPRADAS) AS CANTIDADES_ADQUIRIDAS, 'MAYOR DEMANDA' AS CATEGORIA, ID_SUCURSAL 
FROM DATOS_COMPRAS
GROUP BY CODIGO_BARRAS, NOMBRE, ID_SUCURSAL
ORDER BY CANTIDADES_ADQUIRIDAS DESC;

SELECT * FROM 
(
((SELECT CODIGO_BARRAS, NOMBRE, SUM(VALOR_COMPRA_TOTAL) AS DINERO_ADQUIRIDO, NULL AS CANTIDADES_ADQUIRIDAS, 'MAYORES INGRESOS' AS CATEGORIA, 
ID_SUCURSAL FROM DATOS_COMPRAS
GROUP BY CODIGO_BARRAS, NOMBRE, ID_SUCURSAL)
UNION ALL
(SELECT CODIGO_BARRAS, NOMBRE, NULL AS DINERO_ADQUIRIDO, SUM(CANT_UNIDADES_COMPRADAS) AS CANTIDADES_ADQUIRIDAS, 'MENOR DEMANDA' AS CATEGORIA, ID_SUCURSAL 
FROM DATOS_COMPRAS
GROUP BY CODIGO_BARRAS, NOMBRE, ID_SUCURSAL))
UNION
(SELECT * FROM MAYOR_DEMANDA)
)
ORDER BY ID_SUCURSAL;

/*
SELECT * FROM 
(
((SELECT CODIGO_BARRAS, NOMBRE, SUM(VALOR_COMPRA_TOTAL) AS DINERO_ADQUIRIDO, NULL AS CANTIDADES_ADQUIRIDAS, 'MAYORES INGRESOS' AS CATEGORIA, 
ID_SUCURSAL FROM DATOS_COMPRAS
GROUP BY CODIGO_BARRAS, NOMBRE, ID_SUCURSAL)
UNION ALL
(SELECT CODIGO_BARRAS, NOMBRE, NULL AS DINERO_ADQUIRIDO, SUM(CANT_UNIDADES_COMPRADAS) AS CANTIDADES_ADQUIRIDAS, 'MENOR DEMANDA' AS CATEGORIA, ID_SUCURSAL 
FROM DATOS_COMPRAS
GROUP BY CODIGO_BARRAS, NOMBRE, ID_SUCURSAL))
UNION
(SELECT * FROM MAYOR_DEMANDA)
)
WHERE ID_SUCURSAL=?
ORDER BY ID_SUCURSAL;

*/
