
SELECT NUMERO_DOCUMENTO, NOMBRE, COUNT(NUMERO_DOCUMENTO) AS COMPRAS_REALIZADAS, ID_SUCURSAL FROM
(
(SELECT COMPRADOR FROM COMPRA)
INNER JOIN
(SELECT * FROM USUARIO)
ON COMPRADOR = NUMERO_DOCUMENTO
)
WHERE ID_SUCURSAL = 517
GROUP BY NUMERO_DOCUMENTO, NOMBRE, ID_SUCURSAL;

/*
SELECT NUMERO_DOCUMENTO, NOMBRE, COUNT(NUMERO_DOCUMENTO) AS COMPRAS_REALIZADAS, ID_SUCURSAL FROM
(
(SELECT COMPRADOR FROM COMPRA)
INNER JOIN
(SELECT * FROM USUARIO)
ON COMPRADOR = NUMERO_DOCUMENTO
)
WHERE ID_SUCURSAL = ?
GROUP BY NUMERO_DOCUMENTO, NOMBRE, ID_SUCURSAL;
*/