DROP VIEW ULTIMOS_PEDIDOS;

CREATE VIEW ULTIMOS_PEDIDOS AS
SELECT CODIGO_BARRAS, NOMBRE, CATEGORIA, ID_PEDIDO, SUCURSAL, fecha_entrega FROM (
    SELECT ID, CODIGO_BARRAS, NOMBRE, CATEGORIA, ID_PEDIDO, PRODUCTO.ID_SUCURSAL AS SUCURSAL, FECHA_ENTREGA FROM PRODUCTO
    INNER JOIN(
    SELECT * FROM PEDIDO)
    ON ID = PRODUCTO.ID_PEDIDO
    ) where (CODIGO_BARRAS, fecha_entrega) IN
    (select CODIGO_BARRAS, max(fecha_entrega) from pedido
    group by CODIGO_BARRAS);

SELECT * FROM ULTIMOS_PEDIDOS;

DROP VIEW PENULTIMOS_PEDIDOS;

CREATE VIEW PENULTIMOS_PEDIDOS AS
SELECT CODIGO_BARRAS, NOMBRE, CATEGORIA, ID_PEDIDO, PRODUCTO.ID_SUCURSAL, MAX(fecha_entrega) AS FECHA_ENTREGA FROM PRODUCTO
INNER JOIN (
    SELECT * FROM PEDIDO)
    ON ID = PRODUCTO.ID_PEDIDO
WHERE NOT EXISTS (SELECT * FROM ULTIMOS_PEDIDOS)
GROUP BY CODIGO_BARRAS, NOMBRE, CATEGORIA, ID_PEDIDO, PRODUCTO.ID_SUCURSAL, fecha_entrega;

SELECT * FROM ULTIMOS_PEDIDOS;

SELECT * FROM
(
    SELECT CODIGO_BARRAS, NOMBRE, CATEGORIA, ID_PEDIDO, SUCURSAL, fecha_entrega AS ULTIMA_ENTREGA
    FROM ULTIMOS_PEDIDOS
    INNER JOIN
    (SELECT CODIGO_BARRAS AS CBARRAS, FECHA_ENTREGA AS PENULTIMA_ENTREGA FROM PENULTIMOS_PEDIDOS)
    ON CBARRAS = ULTIMOS_PEDIDOS.CODIGO_BARRAS
    WHERE PENULTIMA_ENTREGA <= FECHA_ENTREGA - INTERVAL '60' DAY
);

/*
    revisa esto por favor.

    SELECT CODIGO_BARRAS, NOMBRE, CATEGORIA, ID_PEDIDO, SUCURSAL, fecha_entrega AS ULTIMA_ENTREGA
    FROM ULTIMOS_PEDIDOS
    INNER JOIN
    (SELECT CODIGO_BARRAS AS CBARRAS, FECHA_ENTREGA AS PENULTIMA_ENTREGA FROM PENULTIMOS_PEDIDOS)
    ON CBARRAS = ULTIMOS_PEDIDOS.CODIGO_BARRAS
    WHERE PENULTIMA_ENTREGA <= FECHA_ENTREGA - INTERVAL '60' DAY
    AND SUCURSAL = ?
*/

SELECT * FROM PEDIDO;

SELECT * FROM PENULTIMOS_PEDIDOS;