ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;
SELECT * FROM (
    (SELECT ID, NOMBRE AS NOMBRE_BEBEDOR, CIUDAD, PRESUPUESTO AS PRESUPUESTO_BEBEDOR 
    FROM BEBEDORES) bebe  
    
    FULL OUTER JOIN 
    
    (SELECT * 
    FROM FRECUENTAN)FREC 
    ON bebe.ID = frec.ID_BEBEDOR   
    
    INNER JOIN
    (SELECT ID, NOMBRE, PRESUPUESTO AS PRESUPUESTO_BAR 
    FROM BARES 
    WHERE PRESUPUESTO = 'Alto')bares
    ON frec.ID_BAR = bares.ID)
WHERE PRESUPUESTO_BEBEDOR = 'Medio' AND PRESUPUESTO_BAR = 'Alto' OR 
    (PRESUPUESTO_BEBEDOR = 'Bajo' AND PRESUPUESTO_BAR IN ('Medio', 'Alto'));
