ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT BEBIDAS.TIPO AS TIPO_BEBIDA, BARES.PRESUPUESTO AS PRESUPUESTO_BARES, COUNT(SIRVEN.ID_BAR) AS CANT_BARES_SIRVEN
FROM BEBIDAS
    INNER JOIN SIRVEN
    ON BEBIDAS.ID = SIRVEN.ID_BEBIDA
    INNER JOIN BARES
    ON BARES.ID = SIRVEN.ID_BAR
GROUP BY BEBIDAS.TIPO, BARES.PRESUPUESTO
ORDER BY BEBIDAS.TIPO;

SELECT BEBIDAS.TIPO AS TIPO_BEBIDA, BEBEDORES.PRESUPUESTO AS PRESUPUESTO_BEBEDORES, COUNT(GUSTAN.ID_BEBEDOR) AS CANT_BEBEDORES_GUSTAN
FROM BEBIDAS
    INNER JOIN GUSTAN
    ON BEBIDAS.ID = GUSTAN.ID_BEBIDA
    INNER JOIN BEBEDORES
    ON BEBEDORES.ID = GUSTAN.ID_BEBEDOR
GROUP BY BEBIDAS.TIPO, BEBEDORES.PRESUPUESTO
ORDER BY BEBIDAS.TIPO;
