ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT BAR.ID_BAR, NOMBRE, PRESUPUESTO, COUNT(BAR.ID_BAR) AS INSTANCIAS
FROM (
        SELECT *
        FROM BARES
            FULL OUTER JOIN (
                SELECT *
                FROM FRECUENTAN
            ) FREC
            ON BARES.ID = FREC.ID_BAR
    ) BAR
    FULL OUTER JOIN SIRVEN
    ON SIRVEN.ID_BAR = BAR.ID
GROUP BY BAR.ID_BAR, NOMBRE, PRESUPUESTO
ORDER BY INSTANCIAS DESC, NOMBRE DESC
FETCH FIRST 10 ROWS ONLY;