ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT DISTINCT CONTEO.CIUDAD, CONTEO.NOMBRE, CONTEO.NUM_BEBEDORES_BEBIDA, GRADO_ALCOHOL
FROM (
        SELECT *
        FROM (
                SELECT ID_BEBEDOR
                FROM GUSTAN
                    INNER JOIN BEBEDORES
                    ON GUSTAN.ID_BEBEDOR = BEBEDORES.ID
                    INNER JOIN (
                        SELECT BEBIDAS.NOMBRE, BEBIDAS.GRADO_ALCOHOL, BARES.CIUDAD, ID_BEBIDA
                        FROM SIRVEN
                            INNER JOIN BEBIDAS
                            ON SIRVEN.ID_BEBIDA = BEBIDAS.ID
                            INNER JOIN BARES
                            ON SIRVEN.ID_BAR = BARES.ID
                        WHERE BARES.PRESUPUESTO = 'Alto'
                            AND GRADO_ALCOHOL BETWEEN 15
                            AND 25
                    ) CIUDAD_BEBIDAS
                    ON GUSTAN.ID_BEBIDA = CIUDAD_BEBIDAS.ID_BEBIDA
                WHERE BEBEDORES.PRESUPUESTO = 'Alto'
                GROUP BY ID_BEBEDOR
                HAVING COUNT(ID_BEBEDOR) > 2
            ) BEBEDORES_APTOS
            INNER JOIN (
                SELECT CIUDAD_BEBIDAS.NOMBRE, CIUDAD_BEBIDAS.GRADO_ALCOHOL, CIUDAD_BEBIDAS.CIUDAD, GUSTAN.ID_BEBEDOR
                FROM GUSTAN
                    INNER JOIN BEBEDORES
                    ON GUSTAN.ID_BEBEDOR = BEBEDORES.ID
                    INNER JOIN (
                        SELECT BEBIDAS.NOMBRE, BEBIDAS.GRADO_ALCOHOL, BARES.CIUDAD, ID_BEBIDA
                        FROM SIRVEN
                            INNER JOIN BEBIDAS
                            ON SIRVEN.ID_BEBIDA = BEBIDAS.ID
                            INNER JOIN BARES
                            ON SIRVEN.ID_BAR = BARES.ID
                        WHERE BARES.PRESUPUESTO = 'Alto'
                            AND GRADO_ALCOHOL BETWEEN 15
                            AND 25
                    ) CIUDAD_BEBIDAS
                    ON GUSTAN.ID_BEBIDA = CIUDAD_BEBIDAS.ID_BEBIDA
                WHERE BEBEDORES.PRESUPUESTO = 'Alto'
            ) INFO_BEBIDAS
            ON BEBEDORES_APTOS.ID_BEBEDOR = INFO_BEBIDAS.ID_BEBEDOR
    ) INFO_BEBIDAS_BEBEDORES
    INNER JOIN (
        SELECT CIUDAD, BEBIDAS.NOMBRE, COUNT(*) AS NUM_BEBEDORES_BEBIDA
        FROM GUSTAN
            INNER JOIN BEBIDAS
            ON BEBIDAS.ID = GUSTAN.ID_BEBIDA
            INNER JOIN BEBEDORES
            ON BEBEDORES.ID = GUSTAN.ID_BEBEDOR
        GROUP BY CIUDAD, BEBIDAS.NOMBRE
    ) CONTEO
    ON INFO_BEBIDAS_BEBEDORES.NOMBRE = CONTEO.NOMBRE
ORDER BY NOMBRE;

SELECT CIUDAD, ID_BEBIDA, COUNT(*) AS NUM_BEBEDORES_BEBIDA
FROM GUSTAN
    INNER JOIN BEBIDAS
    ON BEBIDAS.ID = GUSTAN.ID_BEBIDA
    INNER JOIN BEBEDORES
    ON BEBEDORES.ID = GUSTAN.ID_BEBEDOR
WHERE GRADO_ALCOHOL BETWEEN 15
    AND 25
    AND BEBEDORES.PRESUPUESTO = 'Alto'
GROUP BY CIUDAD, ID_BEBIDA
ORDER BY ID_BEBIDA;

SELECT *
FROM GUSTAN
    INNER JOIN BEBIDAS
    ON BEBIDAS.ID = GUSTAN.ID_BEBIDA
    INNER JOIN BEBEDORES
    ON BEBEDORES.ID = GUSTAN.ID_BEBEDOR
WHERE GRADO_ALCOHOL BETWEEN 15
    AND 25
    AND BEBEDORES.PRESUPUESTO = 'Alto'
AND ID_BEBIDA=103;