ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT COUNT_BEBEDORES.TIPO_BEBIDA, COUNT_BEBEDORES.PRESUPUESTO_BARES, CANT_BARES_SIRVEN, PRESUPUESTO_BEBEDORES, CANT_BEBEDORES_GUSTAN
FROM (
        SELECT BEBIDAS.TIPO AS TIPO_BEBIDA, BARES.PRESUPUESTO AS PRESUPUESTO_BARES, COUNT(SIRVEN.ID_BAR) AS CANT_BARES_SIRVEN
        FROM BEBIDAS
            INNER JOIN SIRVEN
            ON BEBIDAS.ID = SIRVEN.ID_BEBIDA
            INNER JOIN BARES
            ON BARES.ID = SIRVEN.ID_BAR
        GROUP BY BEBIDAS.TIPO, BARES.PRESUPUESTO
    ) COUNT_VENDEN
    INNER JOIN (
        SELECT BEBIDAS.TIPO AS TIPO_BEBIDA, BEBEDORES.PRESUPUESTO AS PRESUPUESTO_BEBEDORES, COUNT(GUSTAN.ID_BEBEDOR) AS CANT_BEBEDORES_GUSTAN, BARES.PRESUPUESTO AS PRESUPUESTO_BARES
        FROM BEBIDAS
            INNER JOIN GUSTAN
            ON BEBIDAS.ID = GUSTAN.ID_BEBIDA
            INNER JOIN BEBEDORES
            ON BEBEDORES.ID = GUSTAN.ID_BEBEDOR
            INNER JOIN SIRVEN
            ON BEBIDAS.ID = SIRVEN.ID_BEBIDA
            INNER JOIN BARES
            ON BARES.ID = SIRVEN.ID_BAR
        GROUP BY BEBIDAS.TIPO, BEBEDORES.PRESUPUESTO, BARES.PRESUPUESTO
    ) COUNT_BEBEDORES
    ON COUNT_BEBEDORES.PRESUPUESTO_BARES = COUNT_VENDEN.PRESUPUESTO_BARES
    AND COUNT_BEBEDORES.TIPO_BEBIDA = COUNT_VENDEN.TIPO_BEBIDA
ORDER BY COUNT_BEBEDORES.TIPO_BEBIDA ASC;