ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT BAR.CIUDAD, BAR.BARES_ALTOS AS BARES_ALTOS, BEBEDOR.BEBEDORES_MEDIOS AS BEBEDORES_MEDIOS
FROM (
        SELECT CIUDAD, COUNT(DISTINCT ID) AS BARES_ALTOS
        FROM BARES
        WHERE PRESUPUESTO = 'Alto'
        GROUP BY CIUDAD
    ) BAR
    LEFT OUTER JOIN (
        SELECT CIUDAD, COUNT(DISTINCT ID) AS BEBEDORES_MEDIOS
        FROM BEBEDORES
        WHERE PRESUPUESTO = 'Medio'
        GROUP BY CIUDAD
    ) BEBEDOR
    ON BEBEDOR.CIUDAD = BAR.CIUDAD;