ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT NOMBRE, PRESUPUESTO, COUNT(ID_BAR) AS INSTANCIAS 
FROM 
    ((SELECT * 
    FROM BARES) bar
FULL OUTER JOIN
    (SELECT * 
    FROM FRECUENTAN)frec
ON bar.ID = frec.ID_BAR)

inner JOIN 
    (SELECT ID_BAR AS ID_SIRV 
    FROM SIRVEN)sirven
ON sirven.ID_SIRV = BAR.ID

GROUP BY ID_BAR, NOMBRE, PRESUPUESTO
ORDER BY INSTANCIAS DESC, NOMBRE
FETCH FIRST 10 ROWS ONLY;