ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT *
FROM (
        SELECT BEBEDORES.ID, BEBEDORES.NOMBRE AS NOMBRE_BEBEDOR, CIUDAD, PRESUPUESTO AS PRESUPUESTO_BEBEDOR, PRESUPUESTO_BAR
        FROM BEBEDORES
            INNER JOIN FRECUENTAN
            ON BEBEDORES.ID = FRECUENTAN.ID_BEBEDOR
            INNER JOIN (
                SELECT ID, PRESUPUESTO AS PRESUPUESTO_BAR
                FROM BARES
                WHERE PRESUPUESTO = 'Alto'
            ) BARES
            ON FRECUENTAN.ID_BAR = BARES.ID
    )
WHERE (PRESUPUESTO_BEBEDOR = 'Medio' AND PRESUPUESTO_BAR = 'Alto')
    OR (PRESUPUESTO_BEBEDOR = 'Bajo' AND PRESUPUESTO_BAR IN ('Medio', 'Alto'));