ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT table_name FROM dba_tables WHERE owner='PARRANDEROS';

SELECT CIUDAD FROM BARES;

SELECT bar.CIUDAD, bar.BARES_ALTOS AS BARES_ALTOS , bebedor.BEBEDORES_MEDIOS AS BEBEDORES_MEDIOS FROM 
(SELECT CIUDAD, COUNT(DISTINCT ID) AS BARES_ALTOS FROM BARES WHERE PRESUPUESTO = 'Alto' GROUP BY CIUDAD) bar
LEFT JOIN
(SELECT CIUDAD, COUNT(DISTINCT ID) AS BEBEDORES_MEDIOS FROM BEBEDORES WHERE PRESUPUESTO = 'Medio' GROUP BY CIUDAD) bebedor
ON bebedor.CIUDAD = bar.ciudad;


SELECT NOMBRE, PRESUPUESTO, COUNT(ID_BAR) AS INSTANCIAS FROM 
(SELECT * FROM BARES) bar
FULL OUTER JOIN
(SELECT * FROM FRECUENTAN)frec
ON bar.ID = frec.ID_BAR
GROUP BY ID_BAR, NOMBRE, PRESUPUESTO
ORDER BY INSTANCIAS DESC, NOMBRE
LIMIT 10;

SELECT * FROM (((SELECT DISTINCT ID, NOMBRE, PRESUPUESTO FROM BEBEDORES WHERE PRESUPUESTO = 'Medio') bebe
INNER JOIN 
(SELECT * FROM FRECUENTAN) frec
ON bebe.ID = frec.ID_BEBEDOR
INNER JOIN
(SELECT ID, NOMBRE, PRESUPUESTO AS PRESUPUESTO_BAR FROM BARES WHERE PRESUPUESTO = 'Alto')bares
ON frec.ID_BAR = bares.ID)
);

SELECT * FROM
(
((SELECT DISTINCT ID, NOMBRE FROM BEBEDORES WHERE PRESUPUESTO = 'Bajo') bebe
INNER JOIN 
(SELECT * FROM FRECUENTAN) frec
ON bebe.ID = frec.ID_BEBEDOR
INNER JOIN
(SELECT * FROM BARES WHERE PRESUPUESTO = 'Alto' OR PRESUPUESTO = 'Medio')bares
ON frec.ID_BAR = bares.ID)
);