CREATE TABLE PRODUCTO (
    CODIGO_BARRAS NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(255) NOT NULL,
    MARCA VARCHAR2(255) NOT NULL,
    CATEGORIA VARCHAR2(255) NOT NULL CHECK(CATEGORIA IN ('Perecedero', 'NoPerecedero', 'Aseo', 'Abarrote', 'Congelado', 'PrendaVestir', 'Mueble', 'Herramienta', 'Electrodomestico')),
    TIPO_PRODUCTO VARCHAR2(255) NOT NULL,
    FECHA_VENCIMIENTO DATE,
    ID_PEDIDO NUMBER NOT NULL,
    FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID),
    ID_SUCURSAL NUMBER NOT NULL,
    FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID),
    INFO_DETALLES NUMBER NOT NULL,
    FOREIGN KEY(INFO_DETALLES) REFERENCES DETALLES_PRODUCTO(ID),
    INFO_MEDICION NUMBER NOT NULL,
    FOREIGN KEY(INFO_MEDICION) REFERENCES MEDICION_PRODUCTO(ID),
    INFO_ALMACENAMIENTO NUMBER NOT NULL,
    FOREIGN KEY(INFO_ALMACENAMIENTO) REFERENCES ALMACENAMIENTO_PRODUCTO(ID)
);