CREATE TABLE PRODUCTOS_PROVISTOS (
    ID_PROVEEDOR NUMBER,
    FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(NIT),
    ID_PRODUCTO NUMBER,
    FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(CODIGO_BARRAS),
    PRIMARY KEY(ID_PROVEEDOR, ID_PRODUCTO)
);