CREATE TABLE REVIEW_PEDIDO (
    ID NUMBER PRIMARY KEY,
    PORCENTAJE_CALIFICACION_CALIDAD NUMBER CHECK(PORCENTAJE_CALIFICACION_CALIDAD BETWEEN 0 AND 100),
    COMENTARIOS_CALIFICACION_CALIDAD VARCHAR2(255),
    ID_PEDIDO NUMBER NOT NULL,
    FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID),
    ID_PROVEEDOR NUMBER NOT NULL,
    FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(NIT)
);