CREATE TABLE USUARIO (
    NUMERO_DOCUMENTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(255) NOT NULL,
    TIPO_CLIENTE VARCHAR2(255) CHECK(TIPO_CLIENTE IN ('PersonaNatural', 'Empresa')),
    TIPO_DOCUMENTO VARCHAR2(255) NOT NULL,
    PALABRA_CLAVE VARCHAR2(255) NOT NULL,
    CORREO VARCHAR2(255) NOT NULL,
    ID_ROL NUMBER NOT NULL,
    FOREIGN KEY(ID_ROL) REFERENCES ROL(ID),
    DIRECCION VARCHAR2(255),
    PUNTOS_ACUMULADOS INTEGER,
    ID_SUCURSAL NUMBER,
    FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID)
);