ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT TABLE_NAME AS NOMBRETABLA, DATA_TYPE AS TIPODEDATOS, COUNT(DATA_TYPE) AS NUMCOLSTIPODATO, AVG(AVG_COL_LEN) AS PROMEDIOLONGITUDCOL
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'PARRANDEROS'
GROUP BY TABLE_NAME, DATA_TYPE
ORDER BY TABLE_NAME ASC, DATA_TYPE ASC, COUNT(DATA_TYPE) ASC;