ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

-- Query for a single column
SELECT NOMBRETABLA, NOMBRECOLUMNA, COUNT(NOMBRERESTRICCION) AS NUMRESTRICCIONES, VOWEL_COUNT
FROM (
        SELECT ALL_TAB_COLUMNS.TABLE_NAME AS NOMBRETABLA, ALL_TAB_COLUMNS.COLUMN_NAME AS NOMBRECOLUMNA, CONSTRAINT_NAME AS NOMBRERESTRICCION, LENGTH(ALL_TAB_COLUMNS.TABLE_NAME) - LENGTH( REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( LOWER(ALL_TAB_COLUMNS.TABLE_NAME), 'a', ''), 'e', ''), 'i', ''), 'o', ''), 'u', '') ) AS VOWEL_COUNT
        FROM ALL_TAB_COLUMNS
            FULL OUTER JOIN ALL_CONS_COLUMNS
            ON ALL_TAB_COLUMNS.TABLE_NAME = ALL_CONS_COLUMNS.TABLE_NAME AND
            ALL_TAB_COLUMNS.COLUMN_NAME = ALL_CONS_COLUMNS.COLUMN_NAME
        WHERE ALL_TAB_COLUMNS.COLUMN_NAME = 'ID' AND
            ALL_TAB_COLUMNS.OWNER = 'PARRANDEROS' AND
            ALL_TAB_COLUMNS.TABLE_NAME = 'BARES' AND
            ALL_TAB_COLUMNS.COLUMN_NAME NOT LIKE ('%R%')
    )
WHERE VOWEL_COUNT <= 2
GROUP BY NOMBRETABLA, NOMBRECOLUMNA, VOWEL_COUNT
ORDER BY NOMBRETABLA ASC, NOMBRECOLUMNA ASC;

-- Query generator for obtaining column information
SELECT COLUMN_NAME AS COLUMNA,
'SELECT NOMBRETABLA, NOMBRECOLUMNA, COUNT(NOMBRERESTRICCION) AS NUMRESTRICCIONES, VOWEL_COUNT
FROM (
        SELECT ALL_TAB_COLUMNS.TABLE_NAME AS NOMBRETABLA, ALL_TAB_COLUMNS.COLUMN_NAME AS NOMBRECOLUMNA, CONSTRAINT_NAME AS NOMBRERESTRICCION, LENGTH(ALL_TAB_COLUMNS.TABLE_NAME) - LENGTH( REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( LOWER(ALL_TAB_COLUMNS.TABLE_NAME), ''a'', ''''), ''e'', ''''), ''i'', ''''), ''o'', ''''), ''u'', '''') ) AS VOWEL_COUNT
        FROM ALL_TAB_COLUMNS
            FULL OUTER JOIN ALL_CONS_COLUMNS
            ON ALL_TAB_COLUMNS.TABLE_NAME = ALL_CONS_COLUMNS.TABLE_NAME AND
            ALL_TAB_COLUMNS.COLUMN_NAME = ALL_CONS_COLUMNS.COLUMN_NAME
        WHERE ALL_TAB_COLUMNS.COLUMN_NAME = ''' || COLUMN_NAME || ''' AND
            ALL_TAB_COLUMNS.OWNER = ''PARRANDEROS'' AND
            ALL_TAB_COLUMNS.TABLE_NAME = ''' || TABLE_NAME || ''' AND
            ALL_TAB_COLUMNS.COLUMN_NAME NOT LIKE (''%R%'')
    )
WHERE VOWEL_COUNT <= 2
GROUP BY NOMBRETABLA, NOMBRECOLUMNA, VOWEL_COUNT
ORDER BY NOMBRETABLA ASC, NOMBRECOLUMNA ASC;' AS SENTENCIA
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'PARRANDEROS' AND
ALL_TAB_COLUMNS.COLUMN_NAME NOT LIKE ('%R%')
AND LENGTH(ALL_TAB_COLUMNS.TABLE_NAME) - LENGTH( REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( LOWER(ALL_TAB_COLUMNS.TABLE_NAME), 'a', ''), 'e', ''), 'i', ''), 'o', ''), 'u', '') ) >= 2;
