ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT ALL_TAB_COLUMNS.TABLE_NAME AS NOMBRETABLA, ALL_TAB_COLUMNS.COLUMN_NAME AS NOMBRECOLUMNA, DATA_TYPE AS TIPODEDATO, CASE
        WHEN CONSTRAINT_NAME IS NULL THEN
            'NO TIENE'
        ELSE
            CONSTRAINT_NAME
    END AS NOMBRERESTRICCION, NULLABLE AS PERMITENULOS
FROM ALL_TAB_COLUMNS
    FULL OUTER JOIN ALL_CONS_COLUMNS
    ON ALL_TAB_COLUMNS.TABLE_NAME = ALL_CONS_COLUMNS.TABLE_NAME AND
    ALL_TAB_COLUMNS.COLUMN_NAME = ALL_CONS_COLUMNS.COLUMN_NAME
WHERE ALL_TAB_COLUMNS.OWNER='PARRANDEROS'
ORDER BY NOMBRETABLA ASC, NOMBRECOLUMNA ASC, NOMBRERESTRICCION ASC;