ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT NOMBRETABLA, NOMBRECOLSPK, TIPODEDATO
FROM (
        SELECT ALL_CONS_COLUMNS.TABLE_NAME AS NOMBRETABLA, ALL_CONS_COLUMNS.COLUMN_NAME AS NOMBRECOLSPK
        FROM ALL_CONSTRAINTS, ALL_CONS_COLUMNS
        WHERE ALL_CONSTRAINTS.CONSTRAINT_TYPE = 'P' AND
            ALL_CONSTRAINTS.CONSTRAINT_NAME = ALL_CONS_COLUMNS.CONSTRAINT_NAME AND
            ALL_CONSTRAINTS.OWNER = ALL_CONS_COLUMNS.OWNER AND
            ALL_CONS_COLUMNS.OWNER = 'PARRANDEROS'
    ) PKS
    INNER JOIN (
        SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE AS TIPODEDATO
        FROM ALL_TAB_COLUMNS
        WHERE OWNER = 'PARRANDEROS'
    ) DTYPE
    ON PKS.NOMBRECOLSPK = DTYPE.COLUMN_NAME AND
    PKS.NOMBRETABLA = DTYPE.TABLE_NAME
ORDER BY NOMBRETABLA;