CREATE TABLE ALMACENAMIENTO_PRODUCTO (
    ID NUMBER PRIMARY KEY,
    ID_CONTENEDOR_ACTUAL NUMBER NOT NULL,
    FOREIGN KEY(ID_CONTENEDOR_ACTUAL) REFERENCES CONTENEDOR(ID),
    EXISTENCIAS_ACTUALES INTEGER NOT NULL,
    NIVEL_REORDEN INTEGER NOT NULL
);