CREATE TABLE COMPRA (
    ID NUMBER PRIMARY KEY,
    VALOR_COMPRA_TOTAL NUMBER,
    URL_FACTURA_ELECTRONICA VARCHAR2(255),
    ESTADO_COMPRA VARCHAR2(255) CHECK(ESTADO_COMPRA IN ('CREADA', 'PAGADA', 'CANCELADA')) NOT NULL,
    COMPRADOR NUMBER NOT NULL,
    FOREIGN KEY(COMPRADOR) REFERENCES USUARIO(NUMERO_DOCUMENTO)
);