CREATE TABLE COMPRA (
    ID NUMBER PRIMARY KEY,
    VALOR_COMPRA_TOTAL NUMBER,
    URL_FACTURA_ELECTRONICA VARCHAR(255),
    ESTADO_COMPRA VARCHAR(255) CHECK(ESTADO IN ('CREADA', 'PAGADA', 'CANCELADA')) NOT NULL,
    COMPRADOR NUMBER NOT NULL FOREIGN KEY REFERENCES USUARIO(NUMERO_DOCUMENTO)
);