CREATE TABLE COMPRA (
    ID INT PRIMARY KEY,
    VALOR_COMPRA_TOTAL FLOAT(24),
    URL_FACTURA_ELECTRONICA VARCHAR(255),
    ESTADO_COMPRA VARCHAR(255) CHECK(ESTADO IN ('CREADA', 'PAGADA', 'CANCELADA')) NOT NULL,
    COMPRADOR INT NOT NULL FOREIGN KEY REFERENCES USUARIO(NUMERO_DOCUMENTO)
);