CREATE TABLE DETALLES_PRODUCTO (
    ID NUMBER PRIMARY KEY,
    PRECIO NUMBER NOT NULL,
    PRECIO_POR_UNIDAD_MEDIDA NUMBER NOT NULL,
    PRESENTACION VARCHAR2(255) NOT NULL,
    CANTIDAD_PRESENTACION NUMBER NOT NULL
);