CREATE TABLE PEDIDO (
    ID NUMBER PRIMARY KEY,
    CANTIDAD_RECOMPRA NUMBER NOT NULL,
    PRECIO_COMPRA_PRODUCTO NUMBER NOT NULL,
    PRECIO_TOTAL_PEDIDO NUMBER,
    FECHA_ESPERADA_ENTREGA DATE NOT NULL,
    FECHA_ENTREGA DATE,
    ESTADO VARCHAR2(255) CHECK(ESTADO IN ('CREADO', 'EN_PROCESO', 'ENTREGADO')),
    SUCURSAL NUMBER NOT NULL FOREIGN KEY REFERENCES SUCURSAL(ID)
);