CREATE TABLE PEDIDOS_PROVEEDOR (
    ID_PEDIDO NUMBER,
    ID_PROVEEDOR NUMBER,
    PRIMARY KEY(ID_PEDIDO, ID_PROVEEDOR),
    ID_PEDIDO FOREIGN KEY REFERENCES PEDIDO(NIT),
    ID_PROVEEDOR FOREIGN KEY REFERENCES PROVEEDOR(NIT)
);