CREATE TABLE PEDIDO (
    ID NUMBER PRIMARY KEY,
    CANTIDAD_RECOMPRA INTEGER NOT NULL,
    PRECIO_COMPRA_PRODUCTO NUMBER NOT NULL,
    PRECIO_TOTAL_PEDIDO NUMBER,
    FECHA_ESPERADA_ENTREGA DATE NOT NULL,
    FECHA_ENTREGA DATE,
    ESTADO VARCHAR2(255) CHECK(ESTADO IN ('CREADO', 'EN_PROCESO', 'ENTREGADO')),
    ID_SUCURSAL NUMBER NOT NULL,
    FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID)
);