CREATE TABLE PEDIDOS_PROVEEDOR (
    PROVEEDOR NUMBER,
    SUPERMERCADO NUMBER,
    PRIMARY KEY(PROVEEDOR, SUPERMERCADO),
    PROVEEDOR FOREIGN KEY REFERENCES PROVEEDOR(NIT),
    SUPERMERCADO FOREIGN KEY REFERENCES SUPERMERCADO(NIT)
);