CREATE TABLE PEDIDO (
    ID INT,
    CANTIDAD_RECOMPRA INT NOT NULL,
    PRECIO_COMPRA_PRODUCTO FLOAT(24) NOT NULL,
    PRECIO_TOTAL_PEDIDO FLOAT(24),
    FECHA_ESPERADA_ENTREGA DATE NOT NULL,
    FECHA_ENTREGA DATE,  
    ESTADO VARCHAR(255) CHECK(ESTADO IN ('CREADO', 'EN_PROCESO', 'ENTREGADO'))
    SUCURSAL INT NOT NULL FOREIGN KEY REFERENCES SUCURSAL(ID),
    PRIMARY KEY ID
)