CREATE TABLE PEDIDOS_PROVEEDOR (
    PROVEEDOR INT,
    SUPERMERCADO INT,
    PRIMARY KEY(PROVEEDOR, SUPERMERCADO),
    PROVEEDOR FOREIGN KEY REFERENCES PROVEEDOR(NIT),
    SUPERMERCADO FOREIGN KEY REFERENCES SUPERMERCADO(NIT)
);