CREATE TABLE PRODUCTO (
    CODIGO_BARRAS NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2 NOT NULL,
    MARCA VARCHAR2 NOT NULL,
    CATEGORIA VARCHAR2 NOT NULL CHECK(CATEGORIA IN ('Perecedero', 'NoPerecedero', 'Aseo', 'Abarrote', 'Congelado', 'PrendaVestir', 'Mueble', 'Herramienta', 'Electrodomestico')),
    TIPO_PRODUCTO VARCHAR2 NOT NULL,
    FECHA_VENCIMIENTO DATE,
    ID_PEDIDO NUMBER NOT NULL FOREIGN KEY REFERENCES PEDIDO(ID),
    ID_SUCURSAL NUMBER NOT NULL FOREIGN KEY REFERENCES SUCURSAL(ID),
    INFO_DETALLES NUMBER NOT NULL FOREIGN KEY REFERENCES DETALLES_PRODUCTO(ID),
    INFO_MEDICION NUMBER NOT NULL FOREIGN KEY REFERENCES MEDICION_PRODUCTO(ID),
    INFO_ALMACENAMIENTO NUMBER NOT NULL FOREIGN KEY REFERENCES ALMACENAMIENTO_PRODUCTO(ID)
);