CREATE TABLE PRODUCTOS_COMPRA (
    COMPRA INT,
    PRODUCTO INT,
    PRIMARY KEY(COMPRA, PRODUCTO),
    COMPRA FOREIGN KEY REFERENCES COMPRA(ID),
    PRODUCTO FOREIGN KEY REFERENCES PRODUCTO(CODIGO_BARRAS)
);