CREATE TABLE PRODUCTOS_COMPRA (
    COMPRA NUMBER,
    PRODUCTO NUMBER,
    PRIMARY KEY(COMPRA, PRODUCTO),
    COMPRA FOREIGN KEY REFERENCES COMPRA(ID),
    PRODUCTO FOREIGN KEY REFERENCES PRODUCTO(CODIGO_BARRAS)
);