CREATE TABLE PRODUCTOS_COMPRA (
    ID_COMPRA NUMBER,
    ID_PRODUCTO NUMBER,
    CANT_UNIDADES_COMPRADAS INTEGER,
    PRIMARY KEY(ID_COMPRA, ID_PRODUCTO),
    FOREIGN KEY(ID_COMPRA) REFERENCES COMPRA(ID),
    FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(CODIGO_BARRAS)
);