CREATE TABLE PROMOCION (
    ID NUMBER PRIMARY KEY,
    REBAJA_EN_PRECIO NUMBER,
    TIPO_PROMOCION VARCHAR(255) NOT NULL CHECK(TIPO_PROMOCION IN ('PagueLleveUnidad', 'DescuentoPorcentaje', 'PagueLleveCantidad', 'Pague1LleveDescuento2', 'Combo')),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    ID_PRODUCTO FOREIGN KEY REFERENCES PRODUCTO(CODIGO_BARRAS) PRIMARY KEY
);