CREATE TABLE PROMOCION (
    ID NUMBER,
    REBAJA_EN_PRECIO NUMBER,
    TIPO_PROMOCION VARCHAR2(255) NOT NULL CHECK(TIPO_PROMOCION IN ('PagueLleveUnidad', 'DescuentoPorcentaje', 'PagueLleveCantidad', 'Pague1LleveDescuento2', 'Combo')),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    ID_PRODUCTO NUMBER,
    CANT_UNIDADES_DISPONIBLES INTEGER NOT NULL,
    TOTAL_UNIDADES_OFRECIDAS INTEGER NOT NULL,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(CODIGO_BARRAS),
    PRIMARY KEY(ID, ID_PRODUCTO)
);