CREATE TABLE REVIEW_PEDIDO (
    ID INT,
    PORCENTAJE_CALIFICACION_CALIDAD INT CHECK(PORCENTAJE_CALIFICACION_CALIDAD BETWEEN 0 AND 100),
    COMENTARIOS_CALIFICACION_CALIDAD VARCHAR(255),
    PEDIDO INT NOT NULL FOREIGN KEY REFERENCES PEDIDO(ID),
    PRIMARY KEY ID
);