CREATE TABLE REVIEW_PEDIDO (
    ID NUMBER,
    PORCENTAJE_CALIFICACION_CALIDAD NUMBER CHECK(PORCENTAJE_CALIFICACION_CALIDAD BETWEEN 0 AND 100),
    COMENTARIOS_CALIFICACION_CALIDAD VARCHAR2(255),
    PEDIDO NUMBER NOT NULL FOREIGN KEY REFERENCES PEDIDO(ID),
    PRIMARY KEY ID
);