CREATE TABLE SUCURSAL (
    ID NUMBER,
    CIUDAD VARCHAR2(255) NOT NULL,
    DIRECCION VARCHAR2(255) NOT NULL,
    NOMBRE VARCHAR2(255) NOT NULL,
    SIZE_SUCURSAL VARCHAR2(255) CHECK(SUCURSAL IN ('Small', 'Medium', 'Big')),
    SUPERMERCADO NUMBER FOREIGN KEY REFERENCES SUPERMERCADO(NIT),
    PRIMARY KEY ID
);