CREATE TABLE SUCURSAL (
    ID NUMBER PRIMARY KEY,
    CIUDAD VARCHAR2(255) NOT NULL,
    DIRECCION VARCHAR2 NOT NULL,
    NOMBRE VARCHAR2(255) NOT NULL,
    SIZE_SUCURSAL VARCHAR2 CHECK(SUCURSAL IN ('Small', 'Medium', 'Big')),
    SEGMENTO_OBJETIVO VARCHAR2
);