CREATE TABLE USUARIO (
    NUMERO_DOCUMENTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(255) NOT NULL,
    TIPO_CLIENTE VARCHAR2(255) CHECK(TIPO_CLIENTE IN ('PersonaNatural', 'Empresa')),
    TIPO_DOCUMENTO VARCHAR2(255) NOT NULL,
    PALABRA_CLAVE VARCHAR2(255) NOT NULL,
    CORREO VARCHAR2(255) NOT NULL,
    ROL VARCHAR2(255) NOT NULL CHECK(ROL IN ('Administrador', 'GerenteGeneral', 'GerenteSucursal', 'Operador', 'Cajero', 'Cliente')),
    DIRECCION VARCHAR2(255),
    PUNTOS_ACUMULADOS VARCHAR2(255),
    ID_SUCURSAL NUMBER,
    FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID)
);